name: Publish release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish-release:
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv publish
